services: 
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: eventos_app 
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_NAME=EventosBack
      - DB_CONNECTION=mysql
      - DB_HOST=eventos_db
      - DB_PORT=3306
      - DB_DATABASE=eventos
      - DB_USERNAME=root
      - DB_PASSWORD=admin123
      - CACHE_DRIVER=redis
      - REDIS_HOST=eventos_cache
      - REDIS_PORT=6379
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailer
      - MAIL_PORT=1025
      - QUEUE_CONNECTION=sync
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - eventos_network
    depends_on:
      - eventos_db
      - eventos_cache

  nginx:
    image: nginx:1.27-alpine
    container_name: eventos_nginx
    restart: unless-stopped
    ports:
      - "8180:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - eventos_network
    depends_on:
      - app

  eventos_db:
    image: mysql:8.4
    container_name: clase_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: eventos
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - eventos_network

  eventos_cache:
    image: redis:7.2-alpine
    container_name: eventos_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - eventos_network
    command: redis-server --appendonly yes

  mailer:
    image: 'axllent/mailpit:latest'
    container_name: eventos_mailer
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      - eventos_network

networks:
  eventos_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local