[mysqld]
# Juego de caracteres moderno y completo (soporta hasta emojis)
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci

# Configuración de red para permitir conexiones externas (Workbench)
bind-address = 0.0.0.0

# Desactivamos el modo estricto para facilitar la importación masiva de datos iniciales
sql_mode=""

[client]
default-character-set=utf8mb4